// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Ponprasath75/QkartGoBackend/internal/ent/product"
	"github.com/Ponprasath75/QkartGoBackend/internal/ent/schema"
	"github.com/Ponprasath75/QkartGoBackend/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCost is the schema descriptor for cost field.
	productDescCost := productFields[4].Descriptor()
	// product.CostValidator is a validator for the "cost" field. It is called by the builders before save.
	product.CostValidator = productDescCost.Validators[0].(func(int) error)
	// productDescRating is the schema descriptor for rating field.
	productDescRating := productFields[5].Descriptor()
	// product.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	product.RatingValidator = productDescRating.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[4].Descriptor()
	// user.BalanceValidator is a validator for the "balance" field. It is called by the builders before save.
	user.BalanceValidator = userDescBalance.Validators[0].(func(int) error)
}
